Algoritmo " 5) Média de notas  "


Var

n1,n2,n3,n4, soma, media : real


Inicio

Escreva (" Digite o valor da 1º nota ")
leia (n1)

Escreva ( " Digite o valor da 2º nota " )
leia (n2)

Escreva ( " Digite o valor da 3º nota " )
leia (n3)

Escreva ( " Digite o valor da 4º nota " )
leia (n4)

soma <- n1 + n2 + n3 + n4
media <- soma / 4

Escreva (" A soma das notas do bimestre são ",soma, " é a media de notas é ", media )

Fimalgoritmo